name:                Tutus
version:             0.1.0.0
github:              "githubuser/TutusProject"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TutusProject#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- filepath
- parsec
- cmdargs
- list-predicate
- pretty-simple
- text
- deepseq
- containers
- time
- clock

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-local-binds

library:
  source-dirs: src

executables:
  Tutus:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tutus
    when:
    - condition: false
      other-modules: Paths_Tutus

benchmarks:
  Tutus-bench:
    main:                Main.hs
    source-dirs:         benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tutus
    - criterion
    - bytestring
    - cassava
